"use client";

import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { BarChart3, Boxes, CalendarRange, ChevronLeft, ChevronRight, Cloud, Download, Eye, EyeOff, LayoutDashboard, LockKeyhole, LogOut, Menu, MessageCircle, Pencil, Phone, PhoneCall, Plus, RefreshCw, ReceiptText, Search, ShoppingCart, Trash2, Trophy, Upload, Users, WifiOff, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { supabase } from "@/lib/supabase";
import { decodeVCardBuffer, formatPhone, normalizePhone, parseVCard, type ParsedVCardContact } from "@/lib/vcard";

type Product={id:string;name:string;icon:string;isActive?:boolean;createdAt?:string};
type Purchase={id:string;productId:string;person:string;plate:string;kg:number;buyPrice:number;dateTime:string;status:string;createdAt?:string};
type Sale={id:string;productId:string;buyer:string;plate:string;kg:number;sellPrice:number;dateTime:string;status:string;createdAt?:string};
type Expense={id:string;title:string;category:string;amount:number;dateTime:string;createdAt?:string};
type Category={id:string;name:string;createdAt?:string};
type ContactCategory={id:string;name:string;createdAt?:string};
type Contact={id:string;name:string;phone:string;category:string;note:string;createdAt?:string};
type ContactImportResult={added:number;skipped:number};
type State={products:Product[];purchases:Purchase[];sales:Sale[];expenses:Expense[];categories:Category[];contactCategories:ContactCategory[];contacts:Contact[]};
type PendingOperation={id:string;action:string;data:Record<string,unknown>;createdAt:string};
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};
type View="dashboard"|"purchases"|"sales"|"ranking"|"expenses"|"contacts"|"reports"|"backup";
type DialogType="purchase"|"editPurchase"|"sale"|"editSale"|"unlockFinance"|"product"|"deleteProduct"|"detail"|"expense"|"category"|"contact"|null;

const EMPTY:State={products:[],purchases:[],sales:[],expenses:[],categories:[],contactCategories:[],contacts:[]};
const PAGE_SIZE=15;
const money=(n:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(n||0);
const kg=(n:number)=>new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2}).format(n||0)+" kg";
const dateTime=(v:string)=>new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));
const localNow=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const localInput=(v:string)=>{const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const norm=(v:string)=>v.toLocaleLowerCase("tr-TR").trim();
const DEFAULT_PRODUCTS=[{name:"Portakal",icon:"🍊"},{name:"Mandalina",icon:"🍊"},{name:"Limon",icon:"🍋"},{name:"Greyfurt",icon:"🟠"},{name:"Nar",icon:"🔴"}];
const DEFAULT_CATEGORIES=["Yemek","Çalışan Ücreti","Yakıt","Nakliye","Diğer"];
const DEFAULT_CONTACT_CATEGORIES=["Tedarikçi","Fabrika","Şoför","Nakliyeci","Çalışan","Diğer"];
const QUEUE_KEY="gurminik_pending_operations_v1",STATE_CACHE_KEY="gurminik_state_cache_v1";
const OFFLINE_ACTIONS=new Set(["addProduct","addPurchase","editPurchase","togglePurchase","addSale","editSale","toggleSale","archiveProduct","addExpense","deleteExpense","addCategory","addContactCategory","addContact","deleteContact"]);
const readQueue=():PendingOperation[]=>{try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||"[]")}catch{return[]}};
const saveQueue=(items:PendingOperation[])=>localStorage.setItem(QUEUE_KEY,JSON.stringify(items));
const whatsAppNumber=(phone:string)=>normalizePhone(phone);

const NAV=[
  ["dashboard","Ana Sayfa",LayoutDashboard],["purchases","Tüm Alışlar",Boxes],["sales","Satışlar",ShoppingCart],
  ["ranking","Sıralamalar",Trophy],["expenses","Giderler",ReceiptText],
  ["contacts","Telefon Numaraları",Phone],["reports","Raporlar",CalendarRange],
  ["backup","Yedekleme",Download],
] as const;

export default function Home(){
  const [session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false);
  const [email,setEmail]=useState("hakdag414@gmail.com"),[password,setPassword]=useState(""),[authMode,setAuthMode]=useState<"signin"|"signup">("signin"),[notice,setNotice]=useState(""),[passwordRecovery,setPasswordRecovery]=useState(false);
  const [state,setState]=useState<State>(EMPTY),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const [view,setView]=useState<View>("dashboard"),[mobile,setMobile]=useState(false),[query,setQuery]=useState("");
  const [dialog,setDialog]=useState<DialogType>(null),[selectedProduct,setSelectedProduct]=useState<string>(""),[selectedPurchase,setSelectedPurchase]=useState<Purchase|null>(null),[selectedSale,setSelectedSale]=useState<Sale|null>(null);
  const [financeUnlocked,setFinanceUnlocked]=useState(false);
  const [online,setOnline]=useState(true),[pendingCount,setPendingCount]=useState(0),[syncing,setSyncing]=useState(false),[syncNotice,setSyncNotice]=useState("");
  const [installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null);
  const [page,setPage]=useState(1),[salePage,setSalePage]=useState(1),[contactPage,setContactPage]=useState(1),[expensePage,setExpensePage]=useState(1);
  const [contactSearch,setContactSearch]=useState(""),[period,setPeriod]=useState<"daily"|"weekly"|"monthly"|"range"|"full">("daily");
  const [reportDate,setReportDate]=useState(localNow().slice(0,10)),[rangeStart,setRangeStart]=useState(localNow().slice(0,10)),[rangeEnd,setRangeEnd]=useState(localNow().slice(0,10));

  const fetchState=useCallback(async()=>{
    const [purchasesResult,salesResult,productsResult,expensesResult,categoriesResult,contactCategoriesResult,contactsResult]=await Promise.all([
      supabase.from("purchases").select("id,product_id,supplier_name,vehicle_plate,quantity_kg,unit_buy_price,transaction_at,status,created_at").order("transaction_at",{ascending:false}),
      supabase.from("sales").select("id,product_id,buyer_name,vehicle_plate,quantity_kg,unit_sale_price,transaction_at,status,created_at").order("transaction_at",{ascending:false}),
      supabase.from("products").select("id,name,icon,is_active,created_at").order("created_at"),
      supabase.from("expenses").select("id,title,category,amount,transaction_at,created_at").order("transaction_at",{ascending:false}),
      supabase.from("expense_categories").select("id,name,created_at").order("name"),
      supabase.from("contact_categories").select("id,name,created_at").order("name"),
      supabase.from("contacts").select("id,name,phone,contact_type,notes,created_at").order("name"),
    ]);
    const failed=[purchasesResult,salesResult,productsResult,expensesResult,categoriesResult,contactCategoriesResult,contactsResult].find(x=>x.error);
    if(failed?.error)throw failed.error;
    return {
      products:(productsResult.data||[]).map(x=>({id:x.id,name:x.name,icon:x.icon||"●",isActive:x.is_active!==false,createdAt:x.created_at})),
      purchases:(purchasesResult.data||[]).map(x=>({id:x.id,productId:x.product_id,person:x.supplier_name,plate:x.vehicle_plate||"",kg:Number(x.quantity_kg),buyPrice:Number(x.unit_buy_price),dateTime:x.transaction_at,status:x.status||"active",createdAt:x.created_at})),
      sales:(salesResult.data||[]).map(x=>({id:x.id,productId:x.product_id,buyer:x.buyer_name||"Alıcı",plate:x.vehicle_plate||"",kg:Number(x.quantity_kg),sellPrice:Number(x.unit_sale_price),dateTime:x.transaction_at,status:x.status||"active",createdAt:x.created_at})),
      expenses:(expensesResult.data||[]).map(x=>({id:x.id,title:x.title,category:x.category,amount:Number(x.amount),dateTime:x.transaction_at,createdAt:x.created_at})),
      categories:(categoriesResult.data||[]).map(x=>({id:x.id,name:x.name,createdAt:x.created_at})),
      contactCategories:(contactCategoriesResult.data||[]).map(x=>({id:x.id,name:x.name,createdAt:x.created_at})),
      contacts:(contactsResult.data||[]).map(x=>({id:x.id,name:x.name,phone:x.phone||"",category:x.contact_type||"Diğer",note:x.notes||"",createdAt:x.created_at})),
    } satisfies State;
  },[]);
  const load=useCallback(async()=>{
    setLoading(true);setError("");
    try{
      const claimed=await supabase.rpc("claim_gurminik_import");if(claimed.error)throw claimed.error;
      let next=await fetchState();
      if(!next.products.length){const inserted=await supabase.from("products").insert(DEFAULT_PRODUCTS);if(inserted.error)throw inserted.error}
      if(!next.categories.length){const inserted=await supabase.from("expense_categories").insert(DEFAULT_CATEGORIES.map(name=>({name})));if(inserted.error)throw inserted.error}
      if(!next.contactCategories.length){const inserted=await supabase.from("contact_categories").insert(DEFAULT_CONTACT_CATEGORIES.map(name=>({name})));if(inserted.error)throw inserted.error}
      if(!next.products.length||!next.categories.length||!next.contactCategories.length)next=await fetchState();
      setState(next);localStorage.setItem(STATE_CACHE_KEY,JSON.stringify(next));
    }
    catch(e){try{const cached=JSON.parse(localStorage.getItem(STATE_CACHE_KEY)||"");if(cached?.products){setState({...EMPTY,...cached});setSyncNotice("Çevrimdışı kayıtlar gösteriliyor.");return}}catch{}setError(e instanceof Error?e.message:"Bulut verileri yüklenemedi.")}
    finally{setLoading(false)}
  },[fetchState]);
  useEffect(()=>{
    let active=true;
    const apply=async(next:Session|null)=>{if(!active)return;setFinanceUnlocked(false);setSession(next);setAuthReady(true);if(next)await load();else setState(EMPTY)};
    void supabase.auth.getSession().then(({data})=>apply(data.session));
    const {data:{subscription}}=supabase.auth.onAuthStateChange((event,next)=>{if(event==="PASSWORD_RECOVERY")setPasswordRecovery(true);void apply(next)});
    return()=>{active=false;subscription.unsubscribe()};
  },[load]);
  const executeMutation=useCallback(async(action:string,data:Record<string,unknown>)=>{
    let result;
    if(action==="addProduct")result=await supabase.from("products").upsert({id:data.id,name:String(data.name),icon:String(data.icon||"●")},{onConflict:"id",ignoreDuplicates:true});
    else if(action==="addPurchase")result=await supabase.from("purchases").upsert({id:data.id,product_id:data.productId,supplier_name:String(data.person),vehicle_plate:String(data.plate).toLocaleUpperCase("tr-TR"),quantity_kg:Number(data.kg),unit_buy_price:Number(data.buyPrice),transaction_at:new Date(String(data.dateTime)).toISOString(),status:"active"},{onConflict:"id",ignoreDuplicates:true});
    else if(action==="editPurchase")result=await supabase.from("purchases").update({product_id:data.productId,supplier_name:String(data.person),vehicle_plate:String(data.plate).toLocaleUpperCase("tr-TR"),quantity_kg:Number(data.kg),unit_buy_price:Number(data.buyPrice),transaction_at:new Date(String(data.dateTime)).toISOString()}).eq("id",data.id);
    else if(action==="togglePurchase")result=await supabase.from("purchases").update({status:data.status}).eq("id",data.id);
    else if(action==="addSale")result=await supabase.from("sales").upsert({id:data.id,product_id:data.productId,buyer_name:String(data.buyer),vehicle_plate:"",quantity_kg:Number(data.kg),unit_sale_price:Number(data.sellPrice),transaction_at:new Date(String(data.dateTime)).toISOString(),status:"active"},{onConflict:"id",ignoreDuplicates:true});
    else if(action==="editSale")result=await supabase.from("sales").update({product_id:data.productId,buyer_name:String(data.buyer),vehicle_plate:"",quantity_kg:Number(data.kg),unit_sale_price:Number(data.sellPrice),transaction_at:new Date(String(data.dateTime)).toISOString()}).eq("id",data.id);
    else if(action==="toggleSale")result=await supabase.from("sales").update({status:data.status}).eq("id",data.id);
    else if(action==="archiveProduct")result=await supabase.from("products").update({is_active:false}).eq("id",data.id);
    else if(action==="addExpense")result=await supabase.from("expenses").upsert({id:data.id,title:String(data.title),category:String(data.category),amount:Number(data.amount),transaction_at:new Date(String(data.dateTime)).toISOString()},{onConflict:"id",ignoreDuplicates:true});
    else if(action==="deleteExpense")result=await supabase.from("expenses").delete().eq("id",data.id);
    else if(action==="addCategory")result=await supabase.from("expense_categories").upsert({id:data.id,name:String(data.name)},{onConflict:"id",ignoreDuplicates:true});
    else if(action==="addContactCategory")result=await supabase.from("contact_categories").upsert({id:data.id,name:String(data.name)},{onConflict:"id",ignoreDuplicates:true});
    else if(action==="addContact")result=await supabase.from("contacts").upsert({id:data.id,name:String(data.name),phone:String(data.phone),notes:String(data.note||""),contact_type:String(data.category||"Diğer")},{onConflict:"id",ignoreDuplicates:true});
    else if(action==="deleteContact")result=await supabase.from("contacts").delete().eq("id",data.id);
    else if(action==="importBackup"){const basePayload={...data,contacts:[]};result=await supabase.rpc("import_gurminik_backup",{payload:basePayload});if(!result.error&&Array.isArray(data.sales)){const saleImport=await supabase.rpc("import_gurminik_sales_backup",{payload:data});if(saleImport.error)throw saleImport.error}if(!result.error&&Array.isArray(data.contactCategories)){const categoryImport=await supabase.rpc("import_gurminik_contact_categories_backup",{payload:data});if(categoryImport.error)throw categoryImport.error}if(!result.error&&Array.isArray(data.contacts)){const contactImport=await supabase.rpc("import_gurminik_contacts_backup",{payload:data});if(contactImport.error)throw contactImport.error}}
    else throw new Error("Geçersiz işlem.");
    if(result.error)throw result.error;
  },[]);
  function applyLocalMutation(action:string,data:Record<string,unknown>){
    const iso=()=>new Date(String(data.dateTime||new Date().toISOString())).toISOString();
    setState(prev=>{const next={...prev};
      if(action==="addProduct")next.products=[...prev.products,{id:String(data.id),name:String(data.name),icon:String(data.icon||"●"),isActive:true}];
      else if(action==="addPurchase")next.purchases=[{id:String(data.id),productId:String(data.productId),person:String(data.person),plate:String(data.plate).toLocaleUpperCase("tr-TR"),kg:Number(data.kg),buyPrice:Number(data.buyPrice),dateTime:iso(),status:"active"},...prev.purchases];
      else if(action==="editPurchase")next.purchases=prev.purchases.map(x=>x.id===data.id?{...x,productId:String(data.productId),person:String(data.person),plate:String(data.plate).toLocaleUpperCase("tr-TR"),kg:Number(data.kg),buyPrice:Number(data.buyPrice),dateTime:iso()}:x);
      else if(action==="togglePurchase")next.purchases=prev.purchases.map(x=>x.id===data.id?{...x,status:String(data.status)}:x);
      else if(action==="addSale")next.sales=[{id:String(data.id),productId:String(data.productId),buyer:String(data.buyer),plate:"",kg:Number(data.kg),sellPrice:Number(data.sellPrice),dateTime:iso(),status:"active"},...prev.sales];
      else if(action==="editSale")next.sales=prev.sales.map(x=>x.id===data.id?{...x,productId:String(data.productId),buyer:String(data.buyer),plate:"",kg:Number(data.kg),sellPrice:Number(data.sellPrice),dateTime:iso()}:x);
      else if(action==="toggleSale")next.sales=prev.sales.map(x=>x.id===data.id?{...x,status:String(data.status)}:x);
      else if(action==="archiveProduct")next.products=prev.products.map(x=>x.id===data.id?{...x,isActive:false}:x);
      else if(action==="addExpense")next.expenses=[{id:String(data.id),title:String(data.title),category:String(data.category),amount:Number(data.amount),dateTime:iso()},...prev.expenses];
      else if(action==="deleteExpense")next.expenses=prev.expenses.filter(x=>x.id!==data.id);
      else if(action==="addCategory")next.categories=[...prev.categories,{id:String(data.id),name:String(data.name)}];
      else if(action==="addContactCategory")next.contactCategories=[...prev.contactCategories,{id:String(data.id),name:String(data.name)}];
      else if(action==="addContact")next.contacts=[...prev.contacts,{id:String(data.id),name:String(data.name),phone:String(data.phone),category:String(data.category||"Diğer"),note:String(data.note||"")}];
      else if(action==="deleteContact")next.contacts=prev.contacts.filter(x=>x.id!==data.id);
      localStorage.setItem(STATE_CACHE_KEY,JSON.stringify(next));return next;
    });
  }
  async function mutate(action:string,data:Record<string,unknown>){
    setError("");const queueOperation=()=>{const items=readQueue();items.push({id:crypto.randomUUID(),action,data,createdAt:new Date().toISOString()});saveQueue(items);setPendingCount(items.length);applyLocalMutation(action,data);setSyncNotice("Kayıt cihazda bekliyor. İnternet gelince otomatik gönderilecek.")};
    if(!navigator.onLine&&OFFLINE_ACTIONS.has(action)){queueOperation();return}
    try{await executeMutation(action,data);await load();setSyncNotice("Bulutla senkronize edildi.")}
    catch(e){const message=e instanceof Error?e.message:"İşlem tamamlanamadı.";if(OFFLINE_ACTIONS.has(action)&&(/fetch|network|internet/i.test(message)||!navigator.onLine)){queueOperation();return}setError(message);throw e}
  }
  const flushQueue=useCallback(async()=>{const items=readQueue();if(!items.length||!navigator.onLine)return;setSyncing(true);let remaining=[...items];try{for(const item of items){await executeMutation(item.action,item.data);remaining=remaining.filter(x=>x.id!==item.id);saveQueue(remaining);setPendingCount(remaining.length)}await load();setSyncNotice("Bekleyen kayıtlar buluta gönderildi.")}catch{setSyncNotice("Bazı kayıtlar hâlâ cihazda bekliyor.")}finally{setSyncing(false)}},[executeMutation,load]);
  useEffect(()=>{setOnline(navigator.onLine);setPendingCount(readQueue().length);const onOnline=()=>{setOnline(true);void flushQueue()},onOffline=()=>setOnline(false);window.addEventListener("online",onOnline);window.addEventListener("offline",onOffline);if(navigator.onLine&&session)void flushQueue();return()=>{window.removeEventListener("online",onOnline);window.removeEventListener("offline",onOffline)}},[flushQueue,session]);
  useEffect(()=>{if(!session)return;let timer:ReturnType<typeof setTimeout>;const channel=supabase.channel("gurminik-live-sync").on("postgres_changes",{event:"*",schema:"public"},()=>{clearTimeout(timer);timer=setTimeout(()=>void load(),500)}).subscribe();return()=>{clearTimeout(timer);void supabase.removeChannel(channel)}},[load,session]);
  useEffect(()=>{if("serviceWorker" in navigator)void navigator.serviceWorker.register("/sw.js");const capture=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent)};window.addEventListener("beforeinstallprompt",capture);return()=>window.removeEventListener("beforeinstallprompt",capture)},[]);
  async function installApp(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);return}window.alert("Telefonda tarayıcının Paylaş veya Menü bölümünden ‘Ana Ekrana Ekle’ seçeneğine dokunun.")}
  async function importBackup(file:File){
    try{const data=JSON.parse(await file.text());const records=Array.isArray(data)?data:(data.records||data.purchases);if(!Array.isArray(records))throw new Error("Geçersiz yedek");if(!window.confirm(`${records.length} alış kaydı ve yedekteki diğer bilgiler buluta eklenecek. Devam edilsin mi?`))return;await mutate("importBackup",Array.isArray(data)?{records:data}:data);setError("")}
    catch{setError("Yedek dosyası okunamadı veya buluta aktarılamadı.")}
  }
  async function importVCardContacts(rows:ParsedVCardContact[]):Promise<ContactImportResult>{
    if(!navigator.onLine)throw new Error("Rehber aktarımı için internet bağlantısı gereklidir.");
    if(!session)throw new Error("Bulut oturumu bulunamadı.");
    const existing=await supabase.from("contacts").select("phone,phone_normalized");
    if(existing.error)throw existing.error;
    const existingKeys=new Set((existing.data||[]).map(row=>String(row.phone_normalized||normalizePhone(row.phone||""))).filter(Boolean));
    const pending=rows.filter(row=>!existingKeys.has(row.phoneKey));
    if(!pending.length)return{added:0,skipped:rows.length};
    const payload=pending.map(row=>({id:crypto.randomUUID(),owner_id:session.user.id,name:row.name||"İsimsiz kişi",phone:formatPhone(row.phone),contact_type:"Diğer",notes:row.unnamed?"vCard aktarımı · İsimsiz kayıt":"vCard aktarımı"}));
    const inserted=await supabase.from("contacts").upsert(payload,{onConflict:"owner_id,phone_normalized",ignoreDuplicates:true}).select("id");
    if(inserted.error)throw inserted.error;
    const added=inserted.data?.length||0;
    await load();setSyncNotice("Rehber kişileri bulutla senkronize edildi.");
    return{added,skipped:rows.length-added};
  }
  async function login(e:FormEvent){e.preventDefault();setError("");setNotice("");if(password.length<6){setError("Şifre en az 6 karakter olmalıdır.");return}if(authMode==="signin"){const {error:signInError}=await supabase.auth.signInWithPassword({email,password});if(signInError)setError("E-posta veya şifre hatalı.")}else{const {data,error:signUpError}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/`}});if(signUpError)setError(signUpError.message);else if(!data.session)setNotice("Onay bağlantısı e-posta adresinize gönderildi. E-postayı onayladıktan sonra giriş yapın.")}}
  async function requestPasswordReset(){setError("");setNotice("");if(!email.trim()){setError("Önce e-posta adresinizi yazın.");return}const {error:resetError}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/`});if(resetError)setError(resetError.message);else setNotice("Şifre yenileme bağlantısı e-posta adresinize gönderildi.")}
  async function updatePassword(e:FormEvent){e.preventDefault();setError("");setNotice("");if(password.length<6){setError("Yeni şifre en az 6 karakter olmalıdır.");return}const {error:updateError}=await supabase.auth.updateUser({password});if(updateError){setError(updateError.message);return}await supabase.auth.signOut();setPasswordRecovery(false);setPassword("");setNotice("Şifreniz yenilendi. Yeni şifrenizle giriş yapabilirsiniz.")}
  async function unlockFinance(passwordToCheck:string){const accountEmail=session?.user.email;if(!accountEmail)return false;const {error:unlockError}=await supabase.auth.signInWithPassword({email:accountEmail,password:passwordToCheck});if(unlockError)return false;setFinanceUnlocked(true);return true}
  if(!authReady)return <main className="gurminik-login text-zinc-400">Güvenli oturum hazırlanıyor…</main>;
  if(passwordRecovery)return <main className="gurminik-login"><form onSubmit={updatePassword} className="gurminik-login-card"><p className="gurminik-eyebrow">GÜVENLİ BULUT HESABI</p><h1>GURMİNİK</h1><p className="gurminik-login-copy">Hesabınız için yeni bir şifre belirleyin.</p><label className="gurminik-field-label">Yeni şifre</label><Input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={6} autoComplete="new-password" required className="gurminik-login-input"/><Button className="gurminik-primary-button mt-5 h-12 w-full">Şifreyi yenile</Button>{error&&<p className="mt-3 text-sm text-red-400">{error}</p>}</form></main>;
  if(!session)return <main className="gurminik-login"><form onSubmit={login} className="gurminik-login-card"><p className="gurminik-eyebrow">GÜVENLİ BULUT HESABI</p><h1>GURMİNİK</h1><p className="gurminik-login-copy">{authMode==="signin"?"Bulut kayıtlarınıza giriş yapın.":"İlk kullanım için güvenli hesabınızı oluşturun."}</p><label className="gurminik-field-label">E-posta</label><Input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" required className="gurminik-login-input"/><label className="gurminik-field-label mt-4">Şifre</label><Input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={6} autoComplete={authMode==="signin"?"current-password":"new-password"} required className="gurminik-login-input"/><Button className="gurminik-primary-button mt-5 h-12 w-full">{authMode==="signin"?"Giriş yap":"Güvenli hesap oluştur"}</Button>{authMode==="signin"&&<button type="button" onClick={()=>void requestPasswordReset()} className="gurminik-login-switch">Şifremi unuttum</button>}<button type="button" onClick={()=>{setAuthMode(authMode==="signin"?"signup":"signin");setError("");setNotice("")}} className="gurminik-login-switch">{authMode==="signin"?"İlk kez kullanıyorum — hesap oluştur":"Zaten hesabım var — giriş yap"}</button>{notice&&<p className="mt-4 rounded-lg bg-emerald-950 p-3 text-sm text-emerald-300">{notice}</p>}{error&&<p className="mt-3 text-sm text-red-400">{error}</p>}</form></main>;

  const live=state.purchases.filter(x=>x.status!=="cancelled");
  const liveSales=state.sales.filter(x=>x.status!=="cancelled");
  const names=Object.values(live.reduce<Record<string,{name:string;kg:number}>>((m,r)=>{const key=norm(r.person);m[key]??={name:r.person,kg:0};m[key].kg+=Number(r.kg);return m},{})).sort((a,b)=>b.kg-a.kg);
  const title=NAV.find(x=>x[0]===view)?.[1]||"";
  const productName=(id:string)=>state.products.find(p=>p.id===id)?.name||"Ürün";
  function openPurchase(productId:string){setSelectedProduct(productId);setDialog("purchase")}
  function openSale(productId:string){setSelectedProduct(productId);setDialog("sale")}
  function requestFinanceUnlock(){setDialog("unlockFinance")}

  return <div className={`gurminik-shell ${mobile?"is-menu-open":""}`}>
    {mobile&&<button className="gurminik-mobile-backdrop lg:hidden" onClick={()=>setMobile(false)} aria-label="Menüyü kapat"/>}
    <aside className={`gurminik-sidebar transition-transform lg:translate-x-0 ${mobile?"translate-x-0":"-translate-x-full"}`}>
      <div className="gurminik-brand"><strong>GURMİNİK</strong><button onClick={()=>setMobile(false)} className="lg:hidden" aria-label="Menüyü kapat"><X/></button></div>
      <nav className="gurminik-nav">{NAV.map(([id,label,Icon])=><button key={id} onClick={()=>{setView(id);setMobile(false);setQuery("");setPage(1)}} className={`gurminik-nav-item ${view===id?"is-active":""}`}><Icon className="size-4"/>{label}</button>)}</nav>
      <div className="gurminik-cloud-box"><div><Cloud className="size-4"/>Bulut bağlantısı aktif</div><span>Supabase kayıtları ve Dropbox gece yedeği korunuyor.</span></div>
      <button onClick={installApp} className="gurminik-logout"><Download className="size-4"/>Telefona yükle</button>
      {financeUnlocked&&<button onClick={()=>setFinanceUnlocked(false)} className="gurminik-logout"><LockKeyhole className="size-4"/>Finansı kilitle</button>}
      <button onClick={()=>supabase.auth.signOut()} className="gurminik-logout"><LogOut className="size-4"/>Çıkış yap</button>
    </aside>
    <main className="gurminik-main">
      <header className="gurminik-topbar"><button className="gurminik-menu-button lg:hidden" onClick={()=>setMobile(true)} aria-label="Menüyü aç"><Menu/></button><div><p>GURMİNİK</p><h2>{title}</h2></div><button className={`gurminik-sync-status ${online?"is-online":"is-offline"}`} onClick={()=>void flushQueue()} disabled={syncing}>{!online?<WifiOff/>:syncing?<RefreshCw className="animate-spin"/>:<Cloud/>}<span>{!online?`Çevrimdışı · ${pendingCount} bekliyor`:pendingCount?`${pendingCount} kayıt gönderilecek`:"Senkronize"}</span></button></header>
      <div className="gurminik-content">
        {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
        {loading&&<div className="mb-5 rounded-xl border bg-white p-4 text-sm text-zinc-500">Bulut kayıtları yükleniyor…</div>}
        {syncNotice&&<div className="gurminik-sync-notice">{syncNotice}<button onClick={()=>setSyncNotice("")}><X/></button></div>}
        {view==="dashboard"&&<Dashboard state={state} live={live} liveSales={liveSales} financeUnlocked={financeUnlocked} requestFinanceUnlock={requestFinanceUnlock} productName={productName} openPurchase={openPurchase} openSale={openSale} setSelectedProduct={setSelectedProduct} setDialog={setDialog} query={query} setQuery={setQuery}/>}
        {view==="purchases"&&<PurchaseList rows={state.purchases} products={state.products} productName={productName} query={query} setQuery={v=>{setQuery(v);setPage(1)}} page={page} setPage={setPage} mutate={mutate} onEdit={r=>{setSelectedPurchase(r);setSelectedProduct(r.productId);setDialog("editPurchase")}}/>}
        {view==="sales"&&<SalesList rows={state.sales} products={state.products} productName={productName} financeUnlocked={financeUnlocked} requestFinanceUnlock={requestFinanceUnlock} page={salePage} setPage={setSalePage} mutate={mutate} onEdit={r=>{if(!financeUnlocked){requestFinanceUnlock();return}setSelectedSale(r);setSelectedProduct(r.productId);setDialog("editSale")}} openSale={openSale}/>}
        {view==="ranking"&&<Ranking state={state} live={live} names={names}/>}
        {view==="expenses"&&<Expenses state={state} page={expensePage} setPage={setExpensePage} mutate={mutate}/>}
        {view==="contacts"&&<Contacts state={state} search={contactSearch} setSearch={v=>{setContactSearch(v);setContactPage(1)}} page={contactPage} setPage={setContactPage} mutate={mutate} importContacts={importVCardContacts}/>}
        {view==="reports"&&<Reports state={state} financeUnlocked={financeUnlocked} requestFinanceUnlock={requestFinanceUnlock} period={period} setPeriod={setPeriod} date={reportDate} setDate={setReportDate} rangeStart={rangeStart} setRangeStart={setRangeStart} rangeEnd={rangeEnd} setRangeEnd={setRangeEnd}/>}
        {view==="backup"&&<Backup state={state} importBackup={importBackup} financeUnlocked={financeUnlocked} requestFinanceUnlock={requestFinanceUnlock}/>}
      </div>
    </main>
    <EntryDialog type={dialog} close={()=>{setDialog(null);setSelectedPurchase(null);setSelectedSale(null)}} state={state} productId={selectedProduct} productName={productName} mutate={mutate} selectedPurchase={selectedPurchase} selectedSale={selectedSale} accountEmail={session.user.email||email} financeUnlocked={financeUnlocked} unlockFinance={unlockFinance}/>
  </div>
}

function Stat({label,value}:{label:string;value:string|number}){return <article className="gurminik-stat"><span>{label}</span><strong>{value}</strong></article>}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <div className="gurminik-searchbox"><Search className="size-4"/><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="border-0 shadow-none focus-visible:ring-0"/></div>}
function Pager({page,setPage,total}:{page:number;setPage:(p:number)=>void;total:number}){const max=Math.ceil(total/PAGE_SIZE);if(max<=1)return null;return <div className="flex items-center justify-center gap-3 border-t p-4"><Button size="icon-sm" variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft/></Button><span className="text-sm font-bold">{page} / {max}</span><Button size="icon-sm" variant="outline" disabled={page===max} onClick={()=>setPage(page+1)}><ChevronRight/></Button></div>}

function Dashboard({state,live,liveSales,financeUnlocked,requestFinanceUnlock,productName,openPurchase,openSale,setSelectedProduct,setDialog,query,setQuery}:{state:State;live:Purchase[];liveSales:Sale[];financeUnlocked:boolean;requestFinanceUnlock:()=>void;productName:(id:string)=>string;openPurchase:(id:string)=>void;openSale:(id:string)=>void;setSelectedProduct:(id:string)=>void;setDialog:(v:DialogType)=>void;query:string;setQuery:(v:string)=>void}){
  const totalKg=live.reduce((s,x)=>s+Number(x.kg),0),cost=live.reduce((s,x)=>s+Number(x.kg)*Number(x.buyPrice),0),expense=state.expenses.reduce((s,x)=>s+Number(x.amount),0),salesKg=liveSales.reduce((s,x)=>s+Number(x.kg),0),salesAmount=liveSales.reduce((s,x)=>s+Number(x.kg)*Number(x.sellPrice),0),profit=salesAmount-cost-expense;
  const results=query?state.purchases.filter(r=>[r.person,r.plate,productName(r.productId)].some(v=>norm(v).includes(norm(query)))).slice(0,15):[];
  return <><div className="gurminik-search-panel"><p>Tüm kayıtlarda ara</p><SearchBox value={query} onChange={setQuery} placeholder="İsim, plaka veya ürün yazın…"/></div>
    {query&&<div className="gurminik-table-panel mb-6"><PurchaseTable rows={results} productName={productName}/></div>}
    <div className="gurminik-summary-grid gurminik-dashboard-stats"><Stat label="Toplam alış kg" value={kg(totalKg)}/><Stat label="Toplam alış tutarı" value={money(cost)}/><Stat label="Toplam gider" value={money(expense)}/><Stat label="Toplam satış kg" value={kg(salesKg)}/><ProtectedStat label="Toplam satış tutarı" value={money(salesAmount)} unlocked={financeUnlocked} onUnlock={requestFinanceUnlock}/><ProtectedStat label="Tahmini kâr" value={money(profit)} unlocked={financeUnlocked} onUnlock={requestFinanceUnlock}/></div>
    <div className="gurminik-section-heading"><div><p>ÜRÜN YÖNETİMİ</p><h3>Ürünler</h3></div><Button variant="outline" onClick={()=>setDialog("product")}><Plus/>Yeni ürün</Button></div>
    <div className="gurminik-product-grid">{state.products.filter(p=>p.isActive!==false).map(p=>{const rows=live.filter(x=>x.productId===p.id),sum=rows.reduce((s,x)=>s+Number(x.kg),0),sold=liveSales.filter(x=>x.productId===p.id).reduce((s,x)=>s+Number(x.kg),0),custom=!DEFAULT_PRODUCTS.some(d=>norm(d.name)===norm(p.name));return <article key={p.id} className="gurminik-product-card">{custom&&<button className="gurminik-product-delete" title={`${p.name} ürününü sil`} aria-label={`${p.name} ürününü sil`} onClick={()=>{setSelectedProduct(p.id);setDialog("deleteProduct")}}><Trash2/></button>}<span>{p.icon}</span><h4>{p.name}</h4><p>Alış {kg(sum)} · Satış {kg(sold)}</p><div className="gurminik-product-actions"><Button onClick={()=>openPurchase(p.id)}><Plus/>Alış</Button><Button className="gurminik-sale-button" onClick={()=>openSale(p.id)}><ShoppingCart/>Satış</Button><Button variant="outline" onClick={()=>{setSelectedProduct(p.id);setDialog("detail")}}>Detay</Button></div></article>})}</div>
  </>}

function ProtectedStat({label,value,unlocked,onUnlock}:{label:string;value:string;unlocked:boolean;onUnlock:()=>void}){return <article className="gurminik-stat gurminik-protected-stat"><span>{label}</span><strong>{unlocked?value:"••••••"}</strong><button onClick={onUnlock}>{unlocked?<EyeOff/>:<LockKeyhole/>}{unlocked?"Görünür":"Şifreyle göster"}</button></article>}

function PurchaseTable({rows,productName,mutate,onEdit}:{rows:Purchase[];productName:(id:string)=>string;mutate?:(a:string,d:Record<string,unknown>)=>Promise<void>;onEdit?:(row:Purchase)=>void}){
  return <Table><TableHeader><TableRow className="bg-zinc-100"><TableHead>Kişi</TableHead><TableHead>Ürün</TableHead><TableHead>Plaka</TableHead><TableHead>Kg</TableHead><TableHead>TL/kg</TableHead><TableHead>Toplam</TableHead><TableHead>Tarih</TableHead><TableHead>Durum</TableHead>{mutate&&<TableHead>İşlem</TableHead>}</TableRow></TableHeader><TableBody>{rows.length?rows.map(r=><TableRow key={r.id} className={r.status==="cancelled"?"opacity-45 line-through":""}><TableCell className="font-bold">{r.person}</TableCell><TableCell>{productName(r.productId)}</TableCell><TableCell>{r.plate}</TableCell><TableCell>{kg(r.kg)}</TableCell><TableCell>{money(r.buyPrice)}</TableCell><TableCell>{money(r.kg*r.buyPrice)}</TableCell><TableCell>{dateTime(r.dateTime)}</TableCell><TableCell>{r.status==="cancelled"?"İptal":"Aktif"}</TableCell>{mutate&&<TableCell><div className="gurminik-row-actions">{onEdit&&<Button size="sm" variant="outline" onClick={()=>onEdit(r)}><Pencil/>Düzenle</Button>}<Button size="sm" variant="outline" onClick={()=>mutate("togglePurchase",{id:r.id,status:r.status==="cancelled"?"active":"cancelled"})}>{r.status==="cancelled"?"Geri al":"İptal et"}</Button></div></TableCell>}</TableRow>):<TableRow><TableCell colSpan={9} className="py-12 text-center text-zinc-500">Kayıt bulunamadı.</TableCell></TableRow>}</TableBody></Table>
}
function PurchaseList({rows,products,productName,query,setQuery,page,setPage,mutate,onEdit}:{rows:Purchase[];products:Product[];productName:(id:string)=>string;query:string;setQuery:(v:string)=>void;page:number;setPage:(p:number)=>void;mutate:(a:string,d:Record<string,unknown>)=>Promise<void>;onEdit:(row:Purchase)=>void}){
  const [productFilter,setProductFilter]=useState("");
  const filtered=rows.filter(r=>(!productFilter||r.productId===productFilter)&&(!query||[r.person,r.plate,productName(r.productId)].some(v=>norm(v).includes(norm(query))))),paged=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  return <><div className="gurminik-record-toolbar gurminik-panel"><SearchBox value={query} onChange={setQuery} placeholder="İsim, plaka veya ürün ara…"/><select value={productFilter} onChange={e=>{setProductFilter(e.target.value);setPage(1)}}><option value="">Tüm ürünler</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><section className="gurminik-table-panel"><PurchaseTable rows={paged} productName={productName} mutate={mutate} onEdit={onEdit}/><Pager page={page} setPage={setPage} total={filtered.length}/></section></>
}

function SaleTable({rows,productName,financeUnlocked,requestFinanceUnlock,mutate,onEdit}:{rows:Sale[];productName:(id:string)=>string;financeUnlocked:boolean;requestFinanceUnlock:()=>void;mutate?:(a:string,d:Record<string,unknown>)=>Promise<void>;onEdit?:(row:Sale)=>void}){
  const hidden=<button className="gurminik-masked-value" onClick={requestFinanceUnlock} title="Şifreyle göster"><LockKeyhole/>Gizli</button>;
  return <Table><TableHeader><TableRow className="bg-zinc-100"><TableHead>Alıcı / Fabrika</TableHead><TableHead>Ürün</TableHead><TableHead>Kg</TableHead><TableHead>Satış TL/kg</TableHead><TableHead>Toplam</TableHead><TableHead>Tarih</TableHead><TableHead>Durum</TableHead>{mutate&&<TableHead>İşlem</TableHead>}</TableRow></TableHeader><TableBody>{rows.length?rows.map(r=><TableRow key={r.id} className={r.status==="cancelled"?"opacity-45 line-through":""}><TableCell className="font-bold">{r.buyer}</TableCell><TableCell>{productName(r.productId)}</TableCell><TableCell>{kg(r.kg)}</TableCell><TableCell>{financeUnlocked?money(r.sellPrice):hidden}</TableCell><TableCell>{financeUnlocked?money(r.kg*r.sellPrice):hidden}</TableCell><TableCell>{dateTime(r.dateTime)}</TableCell><TableCell>{r.status==="cancelled"?"İptal":"Aktif"}</TableCell>{mutate&&<TableCell><div className="gurminik-row-actions">{onEdit&&<Button size="sm" variant="outline" onClick={()=>onEdit(r)}><Pencil/>Düzenle</Button>}<Button size="sm" variant="outline" onClick={()=>mutate("toggleSale",{id:r.id,status:r.status==="cancelled"?"active":"cancelled"})}>{r.status==="cancelled"?"Geri al":"İptal et"}</Button></div></TableCell>}</TableRow>):<TableRow><TableCell colSpan={8} className="py-12 text-center text-zinc-500">Satış kaydı bulunamadı.</TableCell></TableRow>}</TableBody></Table>
}
function SalesList({rows,products,productName,financeUnlocked,requestFinanceUnlock,page,setPage,mutate,onEdit,openSale}:{rows:Sale[];products:Product[];productName:(id:string)=>string;financeUnlocked:boolean;requestFinanceUnlock:()=>void;page:number;setPage:(p:number)=>void;mutate:(a:string,d:Record<string,unknown>)=>Promise<void>;onEdit:(row:Sale)=>void;openSale:(id:string)=>void}){
  const [search,setSearch]=useState(""),[productFilter,setProductFilter]=useState("");
  const filtered=rows.filter(r=>(!productFilter||r.productId===productFilter)&&(!search||[r.buyer,productName(r.productId)].some(v=>norm(v).includes(norm(search))))),paged=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),live=rows.filter(x=>x.status!=="cancelled"),totalKg=live.reduce((s,x)=>s+Number(x.kg),0),totalAmount=live.reduce((s,x)=>s+Number(x.kg)*Number(x.sellPrice),0);
  return <><div className="gurminik-toolbar"><div className="gurminik-summary-grid gurminik-sales-summary"><Stat label="Aktif satış" value={live.length}/><Stat label="Toplam satış kg" value={kg(totalKg)}/><ProtectedStat label="Toplam satış tutarı" value={money(totalAmount)} unlocked={financeUnlocked} onUnlock={requestFinanceUnlock}/></div><Button onClick={()=>openSale(products.find(p=>p.isActive!==false)?.id||"")} disabled={!products.some(p=>p.isActive!==false)}><ShoppingCart/>Yeni satış</Button></div><div className="gurminik-record-toolbar gurminik-panel"><SearchBox value={search} onChange={v=>{setSearch(v);setPage(1)}} placeholder="Alıcı veya ürün ara…"/><select value={productFilter} onChange={e=>{setProductFilter(e.target.value);setPage(1)}}><option value="">Tüm ürünler</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><section className="gurminik-table-panel"><SaleTable rows={paged} productName={productName} financeUnlocked={financeUnlocked} requestFinanceUnlock={requestFinanceUnlock} mutate={mutate} onEdit={onEdit}/><Pager page={page} setPage={setPage} total={filtered.length}/></section></>
}

function Ranking({state,live,names}:{state:State;live:Purchase[];names:{name:string;kg:number}[]}){
  const list=(rows:Purchase[])=>Object.values(rows.reduce<Record<string,{name:string;kg:number}>>((m,r)=>{const k=norm(r.person);m[k]??={name:r.person,kg:0};m[k].kg+=Number(r.kg);return m},{})).sort((a,b)=>b.kg-a.kg);
  return <div className="gurminik-ranking-grid"><RankCard title="Tüm ürünler" rows={names}/>{state.products.map(p=><RankCard key={p.id} title={p.name} rows={list(live.filter(x=>x.productId===p.id))}/>)}</div>
}
function RankCard({title,rows}:{title:string;rows:{name:string;kg:number}[]}){return <article className="gurminik-ranking-card"><h3>{title}</h3>{rows.length?rows.map((r,i)=><div key={r.name} className="gurminik-rank-row"><span>{i+1}</span><strong>{r.name}</strong><b>{kg(r.kg)}</b></div>):<p className="py-8 text-center text-zinc-500">Kayıt yok.</p>}</article>}

function Expenses({state,page,setPage,mutate}:{state:State;page:number;setPage:(p:number)=>void;mutate:(a:string,d:Record<string,unknown>)=>Promise<void>}){
  const [search,setSearch]=useState(""),[category,setCategory]=useState("");
  const now=new Date(),filtered=state.expenses.filter(x=>(!category||x.category===category)&&(!search||[x.title,x.category].some(v=>norm(v).includes(norm(search))))),rows=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),total=state.expenses.reduce((s,x)=>s+Number(x.amount),0),monthTotal=state.expenses.filter(x=>{const d=new Date(x.dateTime);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()}).reduce((s,x)=>s+Number(x.amount),0);
  const categoryTotals=state.categories.map(c=>({name:c.name,total:state.expenses.filter(x=>x.category===c.name).reduce((s,x)=>s+Number(x.amount),0)})).sort((a,b)=>b.total-a.total);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form).entries()) as Record<string,unknown>;data.id=crypto.randomUUID();try{await mutate("addExpense",data);form.reset()}catch{}}
  async function addCategory(){const name=window.prompt("Yeni gider kategorisinin adı:")?.trim();if(!name)return;if(state.categories.some(c=>norm(c.name)===norm(name))){window.alert("Bu kategori zaten mevcut.");return}await mutate("addCategory",{id:crypto.randomUUID(),name})}
  return <><div className="gurminik-summary-grid gurminik-expense-summary"><Stat label="Toplam gider" value={money(total)}/><Stat label="Bu ay" value={money(monthTotal)}/><Stat label="Gider kaydı" value={state.expenses.length}/><Stat label="Kategori" value={state.categories.length}/></div><div className="gurminik-expense-layout"><form onSubmit={submit} className="gurminik-panel gurminik-inline-form"><div className="gurminik-block-heading"><p>YENİ GİDER</p><h3>Gider Kaydı Ekle</h3></div><div className="gurminik-form-grid"><Field name="title" label="Açıklama" placeholder="Örn. 10 adet yemek"/><Field name="amount" label="Tutar (TL)" type="number"/><label>Kategori<select name="category" required defaultValue={state.categories[0]?.name||""}>{state.categories.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label><Field name="dateTime" label="Tarih ve saat" type="datetime-local" defaultValue={localNow()}/></div><div className="gurminik-form-actions"><Button type="button" variant="outline" onClick={addCategory}><Plus/>Yeni kategori</Button><Button type="submit">Gideri kaydet</Button></div></form><aside className="gurminik-panel gurminik-category-panel"><div className="gurminik-block-heading"><p>KATEGORİ DAĞILIMI</p><h3>Kategori Toplamları</h3></div>{categoryTotals.map(x=><div className="gurminik-metric-row" key={x.name}><span>{x.name}</span><strong>{money(x.total)}</strong></div>)}</aside></div><div className="gurminik-record-toolbar gurminik-panel"><SearchBox value={search} onChange={v=>{setSearch(v);setPage(1)}} placeholder="Gider veya kategori ara…"/><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">Tüm kategoriler</option>{state.categories.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></div><div className="gurminik-table-panel"><Table><TableHeader><TableRow className="bg-zinc-100"><TableHead>Açıklama</TableHead><TableHead>Kategori</TableHead><TableHead>Tutar</TableHead><TableHead>Tarih</TableHead><TableHead>İşlem</TableHead></TableRow></TableHeader><TableBody>{rows.length?rows.map(x=><TableRow key={x.id}><TableCell className="font-bold">{x.title}</TableCell><TableCell>{x.category}</TableCell><TableCell>{money(x.amount)}</TableCell><TableCell>{dateTime(x.dateTime)}</TableCell><TableCell><Button variant="outline" size="sm" onClick={()=>{if(window.confirm("Bu gider kaydı silinsin mi?"))mutate("deleteExpense",{id:x.id})}}>Sil</Button></TableCell></TableRow>):<TableRow><TableCell colSpan={5} className="py-12 text-center text-zinc-500">Gösterilecek gider bulunamadı.</TableCell></TableRow>}</TableBody></Table><Pager page={page} setPage={setPage} total={filtered.length}/></div></>
}

function Contacts({state,search,setSearch,page,setPage,mutate,importContacts}:{state:State;search:string;setSearch:(v:string)=>void;page:number;setPage:(p:number)=>void;mutate:(a:string,d:Record<string,unknown>)=>Promise<void>;importContacts:(rows:ParsedVCardContact[])=>Promise<ContactImportResult>}){
  const [category,setCategory]=useState(""),[previewOpen,setPreviewOpen]=useState(false),[previewRows,setPreviewRows]=useState<ParsedVCardContact[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[invalid,setInvalid]=useState(0),[fileDuplicates,setFileDuplicates]=useState(0),[fileName,setFileName]=useState(""),[importing,setImporting]=useState(false),[importMessage,setImportMessage]=useState("");
  const contacts=state.contacts,existingKeys=useMemo(()=>new Set(contacts.map(x=>normalizePhone(x.phone)).filter(Boolean)),[contacts]),searchDigits=search.replace(/\D/g,""),phoneQuery=searchDigits.startsWith("0")?"90"+searchDigits.slice(1):searchDigits,filtered=contacts.filter(x=>(!category||x.category===category)&&(!search||[x.name,x.phone,x.category,x.note].some(v=>norm(v).includes(norm(search)))||(phoneQuery&&normalizePhone(x.phone).includes(phoneQuery)))),rows=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  const newPreviewRows=previewRows.filter(row=>!existingKeys.has(row.phoneKey)),alreadyExisting=previewRows.length-newPreviewRows.length,selectedRows=newPreviewRows.filter(row=>selected.has(row.id));
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form).entries()) as Record<string,unknown>;const phone=formatPhone(String(data.phone||""));if(!normalizePhone(phone)){setImportMessage("Telefon numarası geçerli değil.");return}if(existingKeys.has(normalizePhone(phone))){setImportMessage("Bu telefon numarası rehberde zaten kayıtlı.");return}data.id=crypto.randomUUID();data.phone=phone;try{await mutate("addContact",data);form.reset();setPage(1);setImportMessage("Telefon numarası kaydedildi.")}catch{}}
  async function addContactCategory(){const name=window.prompt("Yeni kişi kategorisinin adı:")?.trim();if(!name)return;if(state.contactCategories.some(c=>norm(c.name)===norm(name))){window.alert("Bu kategori zaten mevcut.");return}await mutate("addContactCategory",{id:crypto.randomUUID(),name})}
  async function chooseVCard(file:File){
    setImportMessage("");
    try{
      const parsed=parseVCard(decodeVCardBuffer(await file.arrayBuffer()));
      if(!parsed.cards)throw new Error("Dosyada vCard kaydı bulunamadı.");
      setFileName(file.name);setPreviewRows(parsed.contacts);setInvalid(parsed.invalid);setFileDuplicates(parsed.duplicatesInFile);setSelected(new Set(parsed.contacts.filter(row=>!existingKeys.has(row.phoneKey)).map(row=>row.id)));setPreviewOpen(true);
    }catch(error){setImportMessage(error instanceof Error?error.message:"VCF dosyası okunamadı.")}
  }
  function toggleRow(id:string){setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})}
  function toggleAll(){setSelected(selectedRows.length===newPreviewRows.length?new Set():new Set(newPreviewRows.map(row=>row.id)))}
  async function confirmImport(){
    if(!selectedRows.length)return;
    setImporting(true);
    try{const result=await importContacts(selectedRows);setPreviewOpen(false);setImportMessage(`${result.added} numara eklendi · ${result.skipped+alreadyExisting+fileDuplicates} mükerrer atlandı · ${invalid} hatalı kayıt bulundu.`);setPage(1)}
    catch(error){setImportMessage(error instanceof Error?error.message:"Rehber buluta aktarılamadı.")}
    finally{setImporting(false)}
  }
  return <>
    <div className="gurminik-contact-summary"><Stat label="Kayıtlı numara" value={contacts.length}/><Stat label="Kategori" value={state.contactCategories.length}/></div>
    {importMessage&&<div className="gurminik-import-result" role="status">{importMessage}</div>}
    <form onSubmit={submit} className="gurminik-panel gurminik-inline-form gurminik-contact-form"><div className="gurminik-block-heading"><p>YENİ TELEFON KAYDI</p><h3>Kişi Ekle</h3></div><div className="gurminik-contact-fields"><Field name="name" label="Adı soyadı" placeholder="Örn. Murat"/><Field name="phone" label="Telefon numarası" type="tel" placeholder="Örn. 0532 000 00 00"/><label>Kategori<select name="category" required defaultValue={state.contactCategories[0]?.name||"Diğer"}>{state.contactCategories.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label><Field name="note" label="Not" required={false} placeholder="Örn. Limon tedarikçisi"/></div><div className="gurminik-form-actions"><Button type="button" variant="outline" onClick={addContactCategory}><Plus/>Yeni kategori</Button><label className="gurminik-vcard-button"><Upload/>Rehberden İçe Aktar<input type="file" accept=".vcf,text/vcard,text/x-vcard" onChange={async e=>{const file=e.target.files?.[0];if(file)await chooseVCard(file);e.currentTarget.value=""}}/></label><Button type="submit">Numarayı kaydet</Button></div></form>
    <div className="gurminik-record-toolbar gurminik-panel"><SearchBox value={search} onChange={setSearch} placeholder="İsim veya telefon numarası ara…"/><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">Tüm kategoriler</option>{state.contactCategories.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></div>
    <div className="gurminik-table-panel"><Table><TableHeader><TableRow className="bg-zinc-100"><TableHead>İsim</TableHead><TableHead>Kategori</TableHead><TableHead>Telefon</TableHead><TableHead>Not</TableHead><TableHead>İşlem</TableHead></TableRow></TableHeader><TableBody>{rows.length?rows.map(x=><TableRow key={x.id}><TableCell className="font-bold">{x.name}</TableCell><TableCell><span className="gurminik-contact-badge">{x.category}</span></TableCell><TableCell><div className="gurminik-contact-actions"><a href={`tel:${x.phone}`}><PhoneCall/>{x.phone}</a><a href={`https://wa.me/${whatsAppNumber(x.phone)}`} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp</a></div></TableCell><TableCell>{x.note||"—"}</TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>{if(window.confirm("Bu telefon kaydı silinsin mi?"))mutate("deleteContact",{id:x.id})}}>Sil</Button></TableCell></TableRow>):<TableRow><TableCell colSpan={5} className="py-12 text-center text-zinc-500">Telefon kaydı bulunamadı.</TableCell></TableRow>}</TableBody></Table><Pager page={page} setPage={setPage} total={filtered.length}/></div>
    <Dialog open={previewOpen} onOpenChange={setPreviewOpen}><DialogContent className="gurminik-vcard-dialog sm:max-w-3xl"><DialogHeader><DialogTitle>Rehber aktarım önizlemesi</DialogTitle><DialogDescription>{fileName} içindeki numaraları kontrol edin. Yalnızca işaretli ve yeni numaralar kaydedilir.</DialogDescription></DialogHeader><div className="gurminik-vcard-summary"><span><strong>{newPreviewRows.length}</strong> eklenebilir</span><span><strong>{alreadyExisting+fileDuplicates}</strong> mükerrer</span><span><strong>{invalid}</strong> hatalı</span></div><div className="gurminik-vcard-toolbar"><Button type="button" variant="outline" onClick={toggleAll} disabled={!newPreviewRows.length}>{selectedRows.length===newPreviewRows.length&&newPreviewRows.length?"Tüm seçimi kaldır":"Tümünü seç"}</Button><span>{selectedRows.length} numara seçildi</span></div><div className="gurminik-vcard-list">{previewRows.length?previewRows.map(row=>{const duplicate=existingKeys.has(row.phoneKey);return <label key={row.id} className={`gurminik-vcard-row ${duplicate?"is-duplicate":""}`}><input type="checkbox" checked={!duplicate&&selected.has(row.id)} disabled={duplicate} onChange={()=>toggleRow(row.id)}/><span className="gurminik-vcard-avatar"><Users/></span><span><strong>{row.name}</strong><small>{row.phone}{row.unnamed?" · İsim bulunamadı":""}</small></span><b>{duplicate?"Zaten kayıtlı":"Yeni"}</b></label>}):<div className="gurminik-vcard-empty">Aktarılabilecek geçerli telefon numarası bulunamadı.</div>}</div><div className="gurminik-vcard-footer"><Button type="button" variant="outline" onClick={()=>setPreviewOpen(false)}>Vazgeç</Button><Button type="button" onClick={confirmImport} disabled={importing||!selectedRows.length}>{importing?<RefreshCw className="animate-spin"/>:<Upload/>}{importing?"Buluta aktarılıyor…":`${selectedRows.length} numarayı aktar`}</Button></div></DialogContent></Dialog>
  </>
}

function pdfAscii(v:unknown){return String(v??"").replace(/[çÇğĞıİöÖşŞüÜ]/g,c=>({ç:"c",Ç:"C",ğ:"g",Ğ:"G",ı:"i",İ:"I",ö:"o",Ö:"O",ş:"s",Ş:"S",ü:"u",Ü:"U"}[c]||c)).replace(/[^\x20-\x7E]/g,"?")}
function pdfEsc(v:unknown){return pdfAscii(v).replace(/([\\()])/g,"\\$1")}
function pdfMoney(n:number){return new Intl.NumberFormat("tr-TR",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)+" TL"}
function assemblePdf(pages:string[][]){const objects:Record<number,string>={1:"<< /Type /Catalog /Pages 2 0 R >>",3:"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",4:"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"},kids:string[]=[];pages.forEach((commands,index)=>{const pageId=5+index*2,contentId=pageId+1,content=commands.join("\n");kids.push(`${pageId} 0 R`);objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${content.length} >>\nstream\n${content}\nendstream`});objects[2]=`<< /Type /Pages /Kids [${kids.join(" ")}] /Count ${pages.length} >>`;let pdf="%PDF-1.4\n";const offsets=[0],max=Math.max(...Object.keys(objects).map(Number));for(let i=1;i<=max;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${max+1}\n0000000000 65535 f \n`;for(let i=1;i<=max;i++)pdf+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";return pdf+`trailer\n<< /Size ${max+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`}
export function createStyledPdf(state:State,title:string,label:string,sourceRecords:Purchase[],sourceExpenses:Expense[],sourceSales:Sale[]=[]){
  const pages:string[][]=[[]];let page=0,y=515;const cmd=(s:string)=>pages[page].push(s),text=(x:number,py:number,size:number,value:unknown,bold=false,color="0 0 0")=>cmd(`BT /${bold?"F2":"F1"} ${size} Tf ${color} rg ${x} ${py} Td (${pdfEsc(value)}) Tj ET`),fill=(x:number,py:number,w:number,h:number,color:string)=>cmd(`${color} rg ${x} ${py} ${w} ${h} re f`),stroke=(x1:number,y1:number,x2:number,y2:number,color=".82 .82 .82")=>cmd(`${color} RG ${x1} ${y1} m ${x2} ${y2} l S`);
  function header(){fill(0,535,842,60,".07 .075 .08");text(30,567,16,"GURMINIK",true,"1 1 1");text(30,548,9,title+"  |  "+label,false,".78 .78 .78")}
  function newPage(){page++;pages.push([]);y=515;header()}
  function ensure(h:number){if(y-h<38)newPage()}
  function section(name:string){ensure(62);y-=11;text(30,y,12,name,true,".14 .14 .14");y-=9;fill(30,y,782,2,".76 .51 .29");y-=13}
  function fit(value:unknown,width:number,size=8){const s=pdfAscii(value),max=Math.max(3,Math.floor(width/(size*.53)));return s.length>max?s.slice(0,max-3)+"...":s}
  function table(headers:string[],widths:number[],rows:unknown[][]){const total=widths.reduce((a,b)=>a+b,0),rowH=20,tableHeader=()=>{ensure(rowH*2);fill(30,y-rowH,total,rowH,".16 .17 .18");let x=34;headers.forEach((h,i)=>{text(x,y-14,7.5,fit(h,widths[i]-8,7.5),true,"1 1 1");x+=widths[i]});y-=rowH};tableHeader();if(!rows.length){text(34,y-14,8,"Kayit bulunamadi.",false,".45 .45 .45");y-=rowH;return}rows.forEach((row,index)=>{if(y-rowH<38){newPage();tableHeader()}if(index%2===1)fill(30,y-rowH,total,rowH,".96 .96 .95");let x=34;row.forEach((cell,i)=>{text(x,y-14,7.5,fit(cell,widths[i]-8,7.5));x+=widths[i]});stroke(30,y-rowH,30+total,y-rowH);y-=rowH});y-=5}
  header();const live=sourceRecords.filter(r=>r.status!=="cancelled"),liveSales=sourceSales.filter(r=>r.status!=="cancelled"),totalKg=live.reduce((s,r)=>s+Number(r.kg),0),salesKg=liveSales.reduce((s,r)=>s+Number(r.kg),0),cost=live.reduce((s,r)=>s+Number(r.kg)*Number(r.buyPrice),0),salesAmount=liveSales.reduce((s,r)=>s+Number(r.kg)*Number(r.sellPrice),0),expense=sourceExpenses.reduce((s,x)=>s+Number(x.amount),0),profit=salesAmount-cost-expense,cards:[[string,unknown],[string,unknown],[string,unknown],[string,unknown],[string,unknown],[string,unknown]]=[["ALIS KG",new Intl.NumberFormat("tr-TR").format(totalKg)],["SATIS KG",new Intl.NumberFormat("tr-TR").format(salesKg)],["ALIS TUTARI",pdfMoney(cost)],["SATIS TUTARI",pdfMoney(salesAmount)],["GIDER",pdfMoney(expense)],["TAHMINI KAR",pdfMoney(profit)]];
  cards.forEach((c,i)=>{const x=30+(i%3)*264,cy=y-Math.floor(i/3)*61;fill(x,cy-55,250,55,".94 .93 .91");text(x+12,cy-20,7.5,c[0],true,".42 .42 .42");text(x+12,cy-42,13,c[1],true,".10 .10 .10")});y-=132;
  section("URUN OZETLERI");const productRows=state.products.map(p=>{const r=live.filter(x=>x.productId===p.id),pk=r.reduce((s,x)=>s+Number(x.kg),0),pc=r.reduce((s,x)=>s+Number(x.kg)*Number(x.buyPrice),0);return[p.name,pk+" kg",pdfMoney(pk?pc/pk:0)+" / kg",pdfMoney(pc),r.length]}).filter(r=>Number.parseFloat(String(r[1]))>0);table(["Urun","Miktar","Ortalama maliyet","Toplam alis","Kayit"],[190,130,165,165,90],productRows);
  section("TEDARIKCI TOPLAMLARI");const suppliers=Object.values(live.reduce<Record<string,{name:string;kg:number}>>((m,r)=>{const key=norm(r.person);m[key]??={name:r.person,kg:0};m[key].kg+=Number(r.kg);return m},{})).sort((a,b)=>b.kg-a.kg);table(["Sira","Kisi","Toplam miktar"],[70,360,210],suppliers.map((x,i)=>[i+1,x.name,x.kg+" kg"]));
  section("ALIS KAYITLARI");table(["Tarih","Kisi","Urun","Plaka","Kg","TL / kg","Toplam","Durum"],[92,120,92,92,70,82,105,72],[...sourceRecords].sort((a,b)=>new Date(b.dateTime).getTime()-new Date(a.dateTime).getTime()).map(r=>[dateTime(r.dateTime),r.person,state.products.find(p=>p.id===r.productId)?.name||"Urun",r.plate,r.kg,pdfMoney(r.buyPrice),pdfMoney(r.kg*r.buyPrice),r.status==="cancelled"?"IPTAL":"AKTIF"]));
  section("SATIS URUN OZETLERI");const saleProductRows=state.products.map(p=>{const r=liveSales.filter(x=>x.productId===p.id),sk=r.reduce((s,x)=>s+Number(x.kg),0),sa=r.reduce((s,x)=>s+Number(x.kg)*Number(x.sellPrice),0);return[p.name,sk+" kg",pdfMoney(sk?sa/sk:0)+" / kg",pdfMoney(sa),r.length]}).filter(r=>Number.parseFloat(String(r[1]))>0);table(["Urun","Satilan miktar","Ort. satis fiyati","Toplam satis","Kayit"],[190,135,165,160,90],saleProductRows);
  section("SATIS KAYITLARI");table(["Tarih","Alici / Fabrika","Urun","Kg","TL / kg","Toplam","Durum"],[105,165,105,85,95,125,90],[...sourceSales].sort((a,b)=>new Date(b.dateTime).getTime()-new Date(a.dateTime).getTime()).map(r=>[dateTime(r.dateTime),r.buyer,state.products.find(p=>p.id===r.productId)?.name||"Urun",r.kg,pdfMoney(r.sellPrice),pdfMoney(r.kg*r.sellPrice),r.status==="cancelled"?"IPTAL":"AKTIF"]));
  section("GIDER KATEGORI OZETI");table(["Kategori","Toplam"],[390,250],state.categories.map(c=>[c.name,pdfMoney(sourceExpenses.filter(x=>x.category===c.name).reduce((s,x)=>s+Number(x.amount),0))]).filter(r=>r[1]!=="0,00 TL"));section("GIDER KAYITLARI");table(["Tarih","Aciklama","Kategori","Tutar"],[120,300,150,150],[...sourceExpenses].sort((a,b)=>new Date(b.dateTime).getTime()-new Date(a.dateTime).getTime()).map(x=>[dateTime(x.dateTime),x.title,x.category,pdfMoney(x.amount)]));
  pages.forEach((p,i)=>{p.push(`BT /F1 7.5 Tf .45 .45 .45 rg 30 17 Td (Olusturma: ${pdfEsc(new Date().toLocaleString("tr-TR"))}) Tj ET`);p.push(`BT /F2 7.5 Tf .25 .25 .25 rg 755 17 Td (Sayfa ${i+1} / ${pages.length}) Tj ET`)});return assemblePdf(pages)
}
function downloadPdf(filename:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:"application/pdf"})),a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}

function Reports({state,financeUnlocked,requestFinanceUnlock,period,setPeriod,date,setDate,rangeStart,setRangeStart,rangeEnd,setRangeEnd}:{state:State;financeUnlocked:boolean;requestFinanceUnlock:()=>void;period:"daily"|"weekly"|"monthly"|"range"|"full";setPeriod:(v:"daily"|"weekly"|"monthly"|"range"|"full")=>void;date:string;setDate:(v:string)=>void;rangeStart:string;setRangeStart:(v:string)=>void;rangeEnd:string;setRangeEnd:(v:string)=>void}){
  const {start,end,label}=useMemo(()=>getRange(period,date,rangeStart,rangeEnd),[period,date,rangeStart,rangeEnd]);
  const inRange=(v:string)=>{const d=new Date(v);return d>=start&&d<end},rows=state.purchases.filter(x=>x.status!=="cancelled"&&inRange(x.dateTime)),sales=state.sales.filter(x=>x.status!=="cancelled"&&inRange(x.dateTime)),exps=state.expenses.filter(x=>inRange(x.dateTime));
  const totalKg=rows.reduce((s,x)=>s+Number(x.kg),0),salesKg=sales.reduce((s,x)=>s+Number(x.kg),0),cost=rows.reduce((s,x)=>s+Number(x.kg)*Number(x.buyPrice),0),salesAmount=sales.reduce((s,x)=>s+Number(x.kg)*Number(x.sellPrice),0),expense=exps.reduce((s,x)=>s+Number(x.amount),0),profit=salesAmount-cost-expense;
  const products=state.products.map(p=>{const r=rows.filter(x=>x.productId===p.id),k=r.reduce((s,x)=>s+Number(x.kg),0),c=r.reduce((s,x)=>s+Number(x.kg)*Number(x.buyPrice),0);return{name:p.name,kg:k,cost:c,avg:k?c/k:0}}).filter(x=>x.kg);
  function print(full=false){if(!financeUnlocked){requestFinanceUnlock();return}const reportRows=full?state.purchases:rows,reportSales=full?state.sales:sales,reportExps=full?state.expenses:exps,reportLabel=full?"Tum zamanlar":label,reportTitle=full?"TAM ISLETME RAPORU":period==="daily"?"GUNLUK RAPOR":period==="weekly"?"HAFTALIK RAPOR":period==="monthly"?"AYLIK RAPOR":"TARIH ARALIGI RAPORU",suffix=full?new Date().toISOString().slice(0,10):period==="range"?`${rangeStart}-${rangeEnd}`:date;downloadPdf(`gurminik-${full?"tam-rapor":period+"-rapor"}-${suffix}.pdf`,createStyledPdf(state,reportTitle,reportLabel,reportRows,reportExps,reportSales))}
  return <><section className="gurminik-report-hero gurminik-panel"><div><p>TAM VERİ DÖKÜMÜ</p><h3>İşletme Raporu</h3><span>Alışlar, satışlar ve giderlerle düzenli tam işletme raporu. Satış tutarları için şifre gerekir.</span></div><Button onClick={()=>print(true)}>{financeUnlocked?<BarChart3/>:<LockKeyhole/>}Tam PDF raporunu indir</Button></section><section className="gurminik-period-panel gurminik-panel"><div className="gurminik-block-heading"><p>DÖNEM RAPORLARI</p><h3>Günlük, Haftalık ve Aylık Rapor</h3></div><div className="gurminik-period-toolbar"><div className="gurminik-period-tabs">{(["daily","weekly","monthly","range"] as const).map(x=><button key={x} className={period===x?"is-active":""} onClick={()=>setPeriod(x)}>{x==="daily"?"Günlük":x==="weekly"?"Haftalık":x==="monthly"?"Aylık":"Tarih aralığı"}</button>)}</div>{period==="range"?<div className="gurminik-range-inputs"><label>Başlangıç<Input type="date" value={rangeStart} onChange={e=>setRangeStart(e.target.value)}/></label><label>Bitiş<Input type="date" value={rangeEnd} onChange={e=>setRangeEnd(e.target.value)}/></label></div>:<label className="gurminik-date-input">Rapor tarihi<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}<Button variant="outline" onClick={()=>print(false)}>{financeUnlocked?<BarChart3/>:<LockKeyhole/>}Bu dönemi PDF indir</Button></div><div className="gurminik-period-label">{label}</div><div className="gurminik-summary-grid gurminik-report-stats"><Stat label="Alınan ürün" value={kg(totalKg)}/><Stat label="Alış tutarı" value={money(cost)}/><Stat label="Giderler" value={money(expense)}/><Stat label="Satılan ürün" value={kg(salesKg)}/><ProtectedStat label="Satış tutarı" value={money(salesAmount)} unlocked={financeUnlocked} onUnlock={requestFinanceUnlock}/><ProtectedStat label="Tahmini kâr" value={money(profit)} unlocked={financeUnlocked} onUnlock={requestFinanceUnlock}/></div><div className="gurminik-period-breakdown"><article><h4>Ürün özeti</h4>{products.length?products.map(x=><div className="gurminik-metric-row" key={x.name}><span>{x.name} · {kg(x.kg)}</span><strong>Ort. {money(x.avg)}/kg</strong></div>):<p className="gurminik-empty">Bu dönemde alış yok.</p>}</article><article><h4>Gider özeti</h4>{state.categories.map(c=>{const amount=exps.filter(x=>x.category===c.name).reduce((s,x)=>s+Number(x.amount),0);return amount?<div className="gurminik-metric-row" key={c.id}><span>{c.name}</span><strong>{money(amount)}</strong></div>:null})}</article></div></section></>
}

function Backup({state,importBackup,financeUnlocked,requestFinanceUnlock}:{state:State;importBackup:(file:File)=>Promise<void>;financeUnlocked:boolean;requestFinanceUnlock:()=>void}){
  function exportBackup(){if(!financeUnlocked){requestFinanceUnlock();return}const payload={app:"GURMİNİK",version:6,exportedAt:new Date().toISOString(),...state,sales:state.sales.map(x=>({...x,productName:state.products.find(p=>p.id===x.productId)?.name||""})),records:state.purchases};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`gurminik-json-yedek-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
  return <><div className="gurminik-backup-notice gurminik-panel"><Cloud/><div><strong>Bulut kayıtlarına ek güvence</strong><p>Bulut alanı dolmadan düzenli olarak JSON yedeği indirin. Bu dosya alışları, satışları, ürünleri, giderleri, rehber kategorilerini ve telefon numaralarını birlikte saklar.</p></div></div><div className="gurminik-backup-grid"><article className="gurminik-backup-card gurminik-panel"><div className="gurminik-backup-icon"><Download/></div><h3>JSON Yedek İndir</h3><p>Uygulamadaki bütün bilgilerin güncel bir kopyasını bilgisayarınıza kaydedin.</p><Button onClick={exportBackup}><Download/>JSON yedeği indir</Button></article><article className="gurminik-backup-card gurminik-panel"><div className="gurminik-backup-icon"><Upload/></div><h3>JSON Yedek Yükle</h3><p>Daha önce indirdiğiniz GURMİNİK JSON yedeğini seçerek bilgileri buluta geri aktarın.</p><label className="gurminik-upload-button"><Upload className="size-4"/>JSON dosyası seç<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(f)await importBackup(f);e.currentTarget.value=""}}/></label></article></div></>
}
function getRange(period:"daily"|"weekly"|"monthly"|"range"|"full",date:string,a:string,b:string){const parse=(v:string)=>{const [y,m,d]=v.split("-").map(Number);return new Date(y,m-1,d)},base=parse(date);let start=base,end=new Date(base),label="";if(period==="weekly"){start=new Date(base);start.setDate(start.getDate()-((start.getDay()+6)%7));end=new Date(start);end.setDate(end.getDate()+7)}else if(period==="monthly"){start=new Date(base.getFullYear(),base.getMonth(),1);end=new Date(base.getFullYear(),base.getMonth()+1,1)}else if(period==="range"){start=parse(a);end=parse(b);if(end<start)[start,end]=[end,start];end.setDate(end.getDate()+1)}else if(period==="full"){start=new Date(0);end=new Date(8640000000000000);label="Tüm zamanlar"}else end.setDate(end.getDate()+1);if(!label)label=period==="monthly"?start.toLocaleDateString("tr-TR",{month:"long",year:"numeric"}):start.toLocaleDateString("tr-TR")+" - "+new Date(end.getTime()-1).toLocaleDateString("tr-TR");return{start,end,label}}

function EntryDialog({type,close,state,productId,productName,mutate,selectedPurchase,selectedSale,accountEmail,financeUnlocked,unlockFinance}:{type:DialogType;close:()=>void;state:State;productId:string;productName:(id:string)=>string;mutate:(a:string,d:Record<string,unknown>)=>Promise<void>;selectedPurchase:Purchase|null;selectedSale:Sale|null;accountEmail:string;financeUnlocked:boolean;unlockFinance:(password:string)=>Promise<boolean>}){
  const [dialogError,setDialogError]=useState(""),[detailUnlocking,setDetailUnlocking]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>,action:string){e.preventDefault();const fd=new FormData(e.currentTarget),data=Object.fromEntries(fd.entries()) as Record<string,unknown>;data.id=action==="editPurchase"?selectedPurchase?.id:action==="editSale"?selectedSale?.id:crypto.randomUUID();if((action==="addPurchase"||action==="addSale")&&!data.productId)data.productId=productId;try{await mutate(action,data);setDialogError("");close()}catch{}}
  async function verifyFinance(e:FormEvent<HTMLFormElement>){e.preventDefault();setDialogError("");const ok=await unlockFinance(String(new FormData(e.currentTarget).get("password")||""));if(ok)close();else setDialogError("Şifre hatalı. Finansal bilgiler açılmadı.")}
  async function verifyDetailFinance(e:FormEvent<HTMLFormElement>){e.preventDefault();setDialogError("");const ok=await unlockFinance(String(new FormData(e.currentTarget).get("password")||""));if(ok)setDetailUnlocking(false);else setDialogError("Şifre hatalı. Ortalama satış fiyatı açılmadı.")}
  async function archiveProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();setDialogError("");const password=String(new FormData(e.currentTarget).get("password")||"");const {error}=await supabase.auth.signInWithPassword({email:accountEmail,password});if(error){setDialogError("Şifre hatalı. Ürün silinmedi.");return}try{await mutate("archiveProduct",{id:productId});close()}catch{setDialogError("Ürün silinemedi. Lütfen tekrar deneyin.")}}
  const live=state.purchases.filter(x=>x.productId===productId&&x.status!=="cancelled"),productSales=state.sales.filter(x=>x.productId===productId&&x.status!=="cancelled"),sumKg=live.reduce((s,x)=>s+Number(x.kg),0),sumCost=live.reduce((s,x)=>s+Number(x.kg)*Number(x.buyPrice),0),soldKg=productSales.reduce((s,x)=>s+Number(x.kg),0),soldAmount=productSales.reduce((s,x)=>s+Number(x.kg)*Number(x.sellPrice),0),averageSale=soldKg?soldAmount/soldKg:0;
  return <Dialog open={!!type} onOpenChange={o=>{if(!o){setDialogError("");close()}}}><DialogContent className={type==="detail"?"gurminik-dialog max-h-[90vh] overflow-auto sm:max-w-5xl":"gurminik-dialog sm:max-w-xl"}><DialogHeader><DialogTitle>{type==="purchase"?productName(productId)+" alış kaydı":type==="editPurchase"?"Alış kaydını düzenle":type==="sale"?productName(productId)+" satış kaydı":type==="editSale"?"Satış kaydını düzenle":type==="unlockFinance"?"Finansal bilgileri aç":type==="product"?"Yeni ürün":type==="deleteProduct"?productName(productId)+" ürününü sil":type==="detail"?productName(productId)+" detayları":type==="expense"?"Yeni gider":type==="category"?"Yeni gider kategorisi":"Yeni telefon numarası"}</DialogTitle><DialogDescription>{type==="deleteProduct"?"Bu işlem ürünü ana sayfadan kaldırır. Eski alış ve satış geçmişi korunur.":type==="unlockFinance"?"Satış tutarı ve tahmini kârı görmek için giriş şifrenizi yeniden yazın.":"Bilgiler kaydedildiği anda bulut veritabanına aktarılır."}</DialogDescription></DialogHeader>
    {type==="purchase"&&<PurchaseEntryForm state={state} productId={productId} submit={submit}/>}
    {type==="editPurchase"&&selectedPurchase&&<form onSubmit={e=>submit(e,"editPurchase")} className="grid gap-4"><label className="grid gap-2 text-sm font-bold">Ürün<select name="productId" defaultValue={selectedPurchase.productId} className="h-10 rounded-md border bg-white px-3">{state.products.filter(p=>p.isActive!==false||p.id===selectedPurchase.productId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Field name="person" label="Getiren kişinin adı" defaultValue={selectedPurchase.person}/><Field name="plate" label="Araç plakası" defaultValue={selectedPurchase.plate}/><Field name="kg" label="Miktar (kg)" type="number" defaultValue={String(selectedPurchase.kg)}/><Field name="buyPrice" label="Alış fiyatı (TL/kg)" type="number" defaultValue={String(selectedPurchase.buyPrice)}/><Field name="dateTime" label="Tarih ve saat" type="datetime-local" defaultValue={localInput(selectedPurchase.dateTime)}/><Button><Pencil/>Değişiklikleri kaydet</Button></form>}
    {type==="sale"&&<SaleEntryForm state={state} productId={productId} submit={submit}/>}
    {type==="editSale"&&selectedSale&&<form onSubmit={e=>submit(e,"editSale")} className="grid gap-4"><label className="grid gap-2 text-sm font-bold">Ürün<select name="productId" defaultValue={selectedSale.productId} className="h-11 rounded-md border bg-white px-3">{state.products.filter(p=>p.isActive!==false||p.id===selectedSale.productId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Field name="buyer" label="Alıcı / fabrika adı" defaultValue={selectedSale.buyer}/><Field name="kg" label="Satış miktarı (kg)" type="number" defaultValue={String(selectedSale.kg)}/><Field name="sellPrice" label="Satış fiyatı (TL/kg)" type="number" defaultValue={String(selectedSale.sellPrice)}/><Field name="dateTime" label="Tarih ve saat" type="datetime-local" defaultValue={localInput(selectedSale.dateTime)}/><Button><Pencil/>Değişiklikleri kaydet</Button></form>}
    {type==="unlockFinance"&&<form onSubmit={verifyFinance} className="grid gap-4"><div className="gurminik-privacy-note"><LockKeyhole/><span>Doğrulama yalnızca bu açık sayfa için geçerlidir. Sayfa yenilenince finansal tutarlar tekrar gizlenir.</span></div><Field name="password" label="Uygulama şifresi" type="password"/>{dialogError&&<p className="text-sm font-bold text-red-600">{dialogError}</p>}<Button><Eye/>Şifreyi doğrula ve göster</Button></form>}
    {type==="product"&&<Form action="addProduct" submit={submit}><Field name="name" label="Ürün adı"/><Field name="icon" label="Simge" placeholder="Örn. 🍎"/></Form>}
    {type==="deleteProduct"&&<form onSubmit={archiveProduct} className="grid gap-4"><div className="gurminik-delete-warning"><Trash2/><span><strong>Ürünü kaldırmak üzeresiniz</strong>Devam etmek için uygulamaya giriş yaptığınız şifreyi yazın.</span></div><Field name="password" label="Uygulama şifresi" type="password"/>{dialogError&&<p className="text-sm font-bold text-red-600">{dialogError}</p>}<Button variant="destructive"><Trash2/>Şifreyi doğrula ve ürünü sil</Button></form>}
    {type==="expense"&&<form onSubmit={e=>submit(e,"addExpense")} className="grid gap-4"><Field name="title" label="Açıklama"/><Field name="amount" label="Tutar (TL)" type="number"/><label className="grid gap-2 text-sm font-bold">Kategori<Select name="category" defaultValue={state.categories[0]?.name}><SelectTrigger className="w-full"><SelectValue placeholder="Kategori seçin"/></SelectTrigger><SelectContent>{state.categories.map(c=><SelectItem key={c.id} value={c.name}>{c.name}</SelectItem>)}</SelectContent></Select></label><Field name="dateTime" label="Tarih ve saat" type="datetime-local" defaultValue={localNow()}/><Button>Buluta kaydet</Button></form>}
    {type==="category"&&<Form action="addCategory" submit={submit}><Field name="name" label="Kategori adı"/></Form>}
    {type==="contact"&&<Form action="addContact" submit={submit}><Field name="name" label="İsim"/><Field name="phone" label="Telefon numarası" type="tel"/><Field name="note" label="Not" required={false} placeholder="Örn. Limon tedarikçisi"/></Form>}
    {type==="detail"&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Toplam miktar" value={kg(sumKg)}/><Stat label="Toplam alış" value={money(sumCost)}/><Stat label="Ortalama maliyet" value={money(sumKg?sumCost/sumKg:0)+"/kg"}/><ProtectedStat label="Ortalama satış fiyatı" value={money(averageSale)+"/kg"} unlocked={financeUnlocked} onUnlock={()=>setDetailUnlocking(true)}/></div>{detailUnlocking&&!financeUnlocked&&<form onSubmit={verifyDetailFinance} className="gurminik-detail-unlock"><div><LockKeyhole/><span>Ortalama satış fiyatını görmek için uygulama şifrenizi yazın.</span></div><Input name="password" type="password" placeholder="Uygulama şifresi" required autoFocus/><Button type="submit"><Eye/>Göster</Button>{dialogError&&<p>{dialogError}</p>}</form>}<div className="overflow-hidden rounded-xl border"><PurchaseTable rows={state.purchases.filter(x=>x.productId===productId)} productName={productName} mutate={mutate}/></div></>}
  </DialogContent></Dialog>
}
function PurchaseEntryForm({state,productId,submit}:{state:State;productId:string;submit:(e:FormEvent<HTMLFormElement>,a:string)=>void}){
  const firstLast=state.purchases.find(x=>x.productId===productId&&x.status!=="cancelled")||state.purchases.find(x=>x.status!=="cancelled");
  const [selectedProduct,setSelectedProduct]=useState(productId),[person,setPerson]=useState(firstLast?.person||""),[plate,setPlate]=useState(firstLast?.plate||""),[amount,setAmount]=useState(""),[price,setPrice]=useState(firstLast?String(firstLast.buyPrice):""),[when,setWhen]=useState(localNow());
  function lastPrice(id:string){return state.purchases.find(x=>x.productId===id&&x.status!=="cancelled")?.buyPrice}
  function productChanged(id:string){setSelectedProduct(id);const remembered=lastPrice(id);setPrice(remembered===undefined?"":String(remembered))}
  function personChanged(value:string){setPerson(value);const match=state.purchases.find(x=>norm(x.person)===norm(value)&&x.plate);if(match)setPlate(match.plate)}
  function plateChanged(value:string){const upper=value.toLocaleUpperCase("tr-TR");setPlate(upper);const match=state.purchases.find(x=>norm(x.plate)===norm(upper));if(match)setPerson(match.person)}
  return <form onSubmit={e=>submit(e,"addPurchase")} className="grid gap-4">
    <label className="grid gap-2 text-sm font-bold">Ürün<select name="productId" value={selectedProduct} onChange={e=>productChanged(e.target.value)} className="h-11 rounded-md border bg-white px-3" required>{state.products.filter(p=>p.isActive!==false).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <label className="grid gap-2 text-sm font-bold">Getiren kişinin adı<Input name="person" value={person} onChange={e=>personChanged(e.target.value)} required autoComplete="off"/></label>
    <label className="grid gap-2 text-sm font-bold">Araç plakası<Input name="plate" value={plate} onChange={e=>plateChanged(e.target.value)} required autoComplete="off"/></label>
    <label className="grid gap-2 text-sm font-bold">Miktar (kg)<Input name="kg" type="number" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label>
    <label className="grid gap-2 text-sm font-bold">Alış fiyatı (TL/kg)<Input name="buyPrice" type="number" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></label>
    <label className="grid gap-2 text-sm font-bold">Tarih ve saat<Input name="dateTime" type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} required/></label>
    <p className="gurminik-form-hint">Seçtiğiniz üründeki son alış fiyatı otomatik gelir; gerektiğinde değiştirebilirsiniz.</p><Button>Buluta kaydet</Button>
  </form>
}
function SaleEntryForm({state,productId,submit}:{state:State;productId:string;submit:(e:FormEvent<HTMLFormElement>,a:string)=>void}){
  const lastForProduct=state.sales.find(x=>x.productId===productId&&x.status!=="cancelled"),last=lastForProduct||state.sales.find(x=>x.status!=="cancelled");
  return <form onSubmit={e=>submit(e,"addSale")} className="grid gap-4"><Field name="buyer" label="Alıcı / fabrika adı" defaultValue={last?.buyer||""}/><Field name="kg" label="Satış miktarı (kg)" type="number"/><Field name="sellPrice" label="Satış fiyatı (TL/kg)" type="number" defaultValue={last?String(last.sellPrice):""}/><Field name="dateTime" label="Tarih ve saat" type="datetime-local" defaultValue={localNow()}/><p className="gurminik-form-hint">Son kullandığınız fabrika ve satış fiyatı otomatik gelir; gerektiğinde değiştirmeniz yeterlidir.</p><Button>Buluta kaydet</Button></form>
}
function Form({action,submit,children}:{action:string;submit:(e:FormEvent<HTMLFormElement>,a:string)=>void;children:ReactNode}){return <form onSubmit={e=>submit(e,action)} className="grid gap-4">{children}<Button>Buluta kaydet</Button></form>}
function Field({name,label,type="text",defaultValue,required=true,placeholder}:{name:string;label:string;type?:string;defaultValue?:string;required?:boolean;placeholder?:string}){return <label className="grid gap-2 text-sm font-bold">{label}<Input name={name} type={type} defaultValue={defaultValue} required={required} placeholder={placeholder} step={type==="number"?"0.01":undefined}/></label>}
